# Generated by Django 3.2.5 on 2024-01-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipeingredientimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredientimage',
            name='extracted',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
