# Generated by Django 3.2.5 on 2024-01-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipeingredientimage_extracted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
